# Etapa 1: build
FROM node:20-alpine AS builder
WORKDIR /app

# Copiamos package.json y package-lock.json
COPY ../frontend/package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del proyecto
COPY ../frontend ./

# Build de Next.js
RUN npm run build

# Etapa 2: producción
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# Copiamos solo lo necesario desde builder
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js

EXPOSE 3000

# Comando que se ejecuta al levantar el contenedor
CMD ["npm", "run", "start"]
