FROM node:20.10

WORKDIR /app

# Copiamos package.json e instalamos dependencias
COPY frontend/package*.json ./
RUN npm install

# Copiamos el resto del frontend
COPY frontend ./

# Exponemos puerto
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "dev"]
